# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sasha's Webpage
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Sasha, and this website is a learning experiment for static
  website development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ap6yc.github.io" # the base hostname & protocol for your site
twitter_username: theAP6YC
github_username:  AP6YC

# Build settings
markdown: kramdown
